### ISSUE TITLE
Tag a "release" before refactoring

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jirahub#17]
Need to tag this repo before @eslavich refactors this repo. The reason is that I want something that used to work with the stuff @SaOgaz set up for Team Indigo.

**Comment by eslavich** [comment]
How about `0.1.0`?

**Comment by pllim** [comment]
The numbering doesn't matter. I just want to be able to go back to a tag when I have to. Thanks!

**Comment by stscicrawford** [comment]
Agreed -- we will have a 0.1.0 release and 0.1.x branch to perserve the current state

**Comment by eslavich** [comment]
The 0.1.x branch and 0.1.0 tag have been created.

**Comment by pllim** [comment]
Thanks!
